version: "2"
services:
  app:
    container_name: app
    restart: on-failure:5 
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: on-failure:5 
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"