version: "2"
services:
  nginx:
    build: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - /var/www:/var/www
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  app:
    container_name: app
    restart: on-failure:5 
    build: .
    environment: 
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=aofoiew031fefedomasd
      - MONGO_HOST=10.5.0.2
      - MONGO_DATABASE=smartgreenhouse
    ports:
      - "3000:3000"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: on-failure:5 
    environment:
        # provide your credentials here
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=aofoiew031fefedomasd
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    command: mongod --auth
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
